draft-wang-ppm-dap-taskprov.md
Here is the doc skeleton as a PR. Feel free to merge and continue working, or you can request changes if you prefer to do things that way. Once you merge, CI will build and upload the changes automatically to https://wangshan.github.io/draft-wang-ppm-dap-taskprov/#go.draft-wang-ppm-dap-taskprov.html.
=> Add skeleton for the document

draft-wang-ppm-dap-taskprov.md
- Wrie `Dp` (short for diff. privacy) instead of `Privacy`. That way we don't end up conflating this (precise) definition of privacy with other definitions. (For example, in the DAP draft, "privacy" refers to an MPC-style definition.)
- Write `Config` instead of `Params`, for consitency with `TaskConfig`, `QueryConfig`, and `VdafConfig`.
- Lift `DpConfig` out of `VdafConfig` as these apply to two separable primitives that we are composing in this application.
- Various editorial nits.
=> Clean up TaskConfig definition

draft-wang-ppm-dap-taskprov.md
Address issue https://github.com/wangshan/draft-wang-ppm-dap-taskprov/issues/8
=> Editorial: Use _ isntead of -

draft-wang-ppm-dap-taskprov.md
Addresses issue https://github.com/wangshan/draft-wang-ppm-dap-taskprov/issues/5
=> Upgrade to DAP-02

draft-wang-ppm-dap-taskprov.md
Addresses issue https://github.com/wangshan/draft-wang-ppm-dap-taskprov/issues/10
=> List contributors in alphabetical order

draft-wang-ppm-dap-taskprov.md
This maps well to any union based structs in implementation
=> Make select branch variable name unique

draft-wang-ppm-dap-taskprov.md
=> Merge pollution security considerations

draft-wang-ppm-dap-taskprov.md
=> Use HKDF to extract task ID and VDAF verify key

draft-wang-ppm-dap-taskprov.md
* Bump references to draft-ietf-ppm-dap-02 to 04
* Bump references to draft-irtf-cfrg-vdaf-03 to 05
* The latest DAP draft drops metadata extensions in favor of per-Aggregator extensions included in the report shares. These new extensions are not well-suited for shared extensions, since we end up blowing up communication cost by transmitting the task configuration twice in the same report.
Including the task configuration in the extensions has another problem: All reports include it, which means it is necessary for the Helper to check that each report in an aggregation job includes the exact same copy of this extension. This adds unnecessary complexity to the spec.
We solve these problems by advertising the task configuration in a header: The Client includes it in its upload request to he …
=> Align taskprov with latest DAP draft

draft-wang-ppm-dap-taskprov.md
=> Align with draft-ietf-ppm-dap-06

draft-wang-ppm-dap-taskprov.md
Closes #6.
Note that this is a wire-breaking change.
=> Align aggregator endpoints with DAP-07

draft-wang-ppm-dap-taskprov.md
Related to PR https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/530 in core DAP
=> Make max batch size optional

draft-wang-ppm-dap-taskprov.md
=> Update DAP and VDAF reference

draft-wang-ppm-dap-taskprov.md
=> Issue 47: client may skip advertising task

draft-wang-ppm-dap-taskprov.md
=> Issue 48: Acknowledge security consideration of having task Author

draft-wang-ppm-dap-taskprov.md
David has sent a few PRs, some of which have helped clarify things a bunch.
cc/ @divergentdave: please double check your address in affiliation.
=> Add @divergentdave to contributors

.github/workflows/archive.yml, .github/workflows/ghpages.yml, .github/workflows/publish.yml, .github/workflows/update.yml, .gitignore, CONTRIBUTING.md, README.md, draft-ietf-ppm-dap-taskprov.md
* Run `make update-files`
* Run `make update`
* Add a doc abbreviation tag
* Resolve all warnings from `xml2rfc`
=> House keeping

draft-ietf-ppm-dap-taskprov.md
=> Address issue 70 - update codepoints

draft-ietf-ppm-dap-taskprov.md
There is no protocol interaction between the Author any party.
=> Forget about informing the Author of opt-out

draft-ietf-ppm-dap-taskprov.md
Account for the following changes in DAP-12:
* "query type" is now called "batch mode"
* `fixed_size` batch mode has been renamed to `leader_selected`
* The `max_batch_query_count` parameter no longer exists
* The `max_batch_size` field for `leader_selected` no longer exists
=> Update query config (*)

draft-ietf-ppm-dap-taskprov.md
Stacked on #82.
Closes #72.
Partially addresses #34.
* Ask IANA to register the extension codepoint
* Ask IANA to create a registry for DP mechanisms
* Add guidance for extending taskbind in the future
* Ask IANA to add "invalidTask" to the URN sub-namespace for DAP
We haven't quite figured out the last of these, so leave it as a TODO.
Future documents might extend the batch config, DP config, or VDAF
config, so it's helpful if these structures are self-contained. To
accomplish this, move the time precision and min batch size parameters
out of BatchConfig into TaskConfig and move the DP mechnaism and config
out of VdafConfig.
=> Flesh out IANA considerations and extending taskbind (*)

draft-ietf-ppm-dap-taskprov.md
=> Address issue 62 - adding task start time

draft-ietf-ppm-dap-taskprov.md
=> Address issue 83 - more bytes for DpMechanism

draft-ietf-ppm-dap-taskprov.md
Stacked on #89.
Closes #88.
This can be expressed as a Taskbind extension.
=> Remove DP mechanisms (*)

draft-ietf-ppm-dap-taskprov.md
Stacked on #90.
Along the same lines as
https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/627
Harmonize the extension points for new batch modes or VDAFs with
Tasbind extensions by following the Tag-Length-Value (TLV) pattern. That
is, encode the variant followed by length-prefixed payload, the format
of which is determined by the variant. This is inteded to make it easier
to extend the document in the future.
This change also has a couple of bug fixes:
* Fix encoding of Prio3Sum config (the circuit now requires a maximum
measurement rather than the bit length of the maximum measurement).
* Add encoding for Prio3MultihotCountVec
﻿﻿
=> Improve extension points for batch modes and VDAFs (*)

draft-ietf-ppm-dap-taskprov.md
=> Fix a typo

draft-ietf-ppm-dap-taskprov.md
=> Add considerations for task enumeration attacks

draft-ietf-ppm-dap-taskprov.md
=> Bump DAP-13 -> 16, VDAF-13 -> 15, and update section references
