- draft-wang-ppm-dap-taskprov.md
- Clean up the introduction. Be sure to mention all the salient points, including that some artifacts are still negotiated out of batnd.
- Spell out "opt-in" versus "opt-out" conditions. This makes the previous {{provisioning-a-task}} section more explicit and adds some additional features.
- Formalize the language in the protocol behavior sections.
- Add notes and an attack to security considerations.
- Move max_bach_lifetime into QueryConfig, as this parameter constrains queries.
- Various editorial things, including aligning with editorial changes in DAP-02.
> Flesh out some of the protocol details

- draft-wang-ppm-dap-taskprov.md
QueryConfig is defined in this spec, not DAP-02.
Thanks to @bhalleycf for flagging.
> Fix an inaccurate comment

- draft-wang-ppm-dap-taskprov.md
This allows us to avoid matching on the type byte more than once in code.
> QueryConfig: Move type byte to just before variant

- draft-wang-ppm-dap-taskprov.md
We use "dap-taskprov-00" right now, the idea being that we would revise this to "dap-taskprov-01" for the next draft. Shan suggests this might end up being a footgun when we have to update to the next draft.
> Use "dap-taskprov" for the salt constant

- draft-wang-ppm-dap-taskprov.md
* Update dap version to 07
* Reverted a change in https://github.com/wangshan/draft-wang-ppm-dap-taskprov/pull/38, because non-unique name in select branch make the syntax parsing in a union based implementation very awkward, see https://github.com/wangshan/draft-wang-ppm-dap-taskprov/pull/17.
* mention DP on DAP draft https://github.com/wangshan/draft-wang-ppm-differential-privacy
> Align with draft-ietf-ppm-dap-07

- draft-wang-ppm-dap-taskprov.md
Address [issue 35](https://github.com/wangshan/draft-wang-ppm-dap-taskprov/issues/35) by removing retry-after.
> Remove retry-after from leader

- draft-wang-ppm-dap-taskprov.md
Closes #23.
Previously we would fail to parse the `TaskConfig` if one of its parameters was not recognized. Modify the wire format so that it is always decodable.
> Opt-out if a task parameter is not recognized

- draft-wang-ppm-dap-taskprov.md
Currently the Helper is supposed to abort an aggregation job that contains a report share that is missing the `taskprov` extension. However because the Helper report shares are encrypted, the Leader has no way of knowing whether the extension is present or not. This means there is no protocol-level mechanism for the Helper to convey which report needs to be removed from the candidate set before retrying.
Instead of aborting, have the Helper simply reject the malformed report.
Clarify a few things while at it.
> Helper: Reject reports with missing extension

- draft-wang-ppm-dap-taskprov.md
This is intended to simplify encoding/decoding of this struct.
> QueryConfig: Move query type to just before the params

- draft-wang-ppm-dap-taskprov.md
Also remove length hints in TLS variants that are mandatory to configure a task.
> Change dp_config to opaque

- draft-wang-ppm-dap-taskprov.md
**Option 2.**
A previous commit f8cedf129c0dfb6a3461b33f90717fcf88cc534b, the `DpConfig` structure was replaced with an opaque byte string that the parties are meant to ignore. We don't want the parties to ignore unrecognized parameters: they should opt out instead. This change specifies that the content should be a `DpConfig`. We also remove the length prefix from that structure, since it's no longer needed.
The same commit removed the length prefixes from `VdafConfig` and `QueryConfig`. This is a regression because it means the encoding of the `TaskConfig` is no longer self-describing. In particular, it forces to conflate opt-out due to unrecognized variants (an unimplemented VDAF, say) with serialization errors. Solve this making the `vdaf_config` and `query_config` fields of the …
> Add back `DpConfig` and make `vdaf_config` and `query_config` opaque

- draft-wang-ppm-dap-taskprov.md
Closes #54.
This commit splits the draft into the task binding extension and a separate section for the optional provisioning mechanism. While at it:
- Fix some editorial issues.
- Rename the extension to "Taskbind".
- Recommend having the author digitally sign the advertised task config. This helps mitigate the risk of malicious Clients DoS'ing an Aggregator.
> Split the draft into task binding and task provisioning

- draft-wang-ppm-dap-taskprov.md
This makes a few editorial fixes throughout the document.
- There's one reference to the payload of the extension left over from past drafts (the payload should now be empty).
- There are contradicting statements that the collector receives task parameters via HTTP headers and directly from the task author. I removed mention of HTTP headers, since the collector only initiates HTTP requests.
- I changed places where mention was made of the collector making an upload request or the helper receiving an upload request.
> Editorial changes

- draft-wang-ppm-dap-taskprov.md
Closes #64.
Current the task ID is computed by hashing the raw `TaskConfig`. Prepend the `TaskConfig` with a salt string so that it's less likely we'll confuse the task ID with the hash of the task config in a different context.
> Add salt to task ID computation (*)

- draft-ietf-ppm-dap-taskprov.md
This was erroneously deleted in a prior commit.
> Add back the expiration date to `TaskConfig`

- draft-ietf-ppm-dap-taskprov.md
Closes #85. We'll consider #88 (whether to remove the DP mechanism and suggest implementations do this in an extension) in a future PR.
Notable features:
* Create a registry for new taskbind extensions
* Make extensions mandatory-to-implement when provisioning a task
cc @martinthomson
> Add an extension field to `TaskConfig` (*)

- draft-ietf-ppm-dap-taskprov.md
Stacked on #91.
* Pass of draft:
* Update section references.
* Improve precision of terminology.
* Remove the "Supporting HPKE Configurations Independent of Tasks" section. This is no longer relevant since we removed support of per-task HPKE configs in DAP draft 12.
* Fix a few typos and minor grammar issues.
* In Security Considerations we recommend digitally signing the task config; mention that we can do this with a Taskbind extension.
* Add a change log.
* Bump base drafts.
> Prepare to cut draft 01

- draft-ietf-ppm-dap-taskprov.md
Both of the relevant fields can include zero-length values in some cases, so this change is required for taskprov to be implementable (while still following the specification).
Also, clean up a comment typo.
> Tweak lower bounds on field lengths to 0 instead of 1.

- draft-ietf-ppm-dap-taskprov.md
This fixes a few editorial issues in references.
* One of the IANA considerations sections had a reference to VDAF that should instead be a reference to DAP.
* There was a reference to `{{Section C of !VDAF}}`. Appendix C is the test vectors. Based on context, I think this should have been a reference to the Prio3 section, so I changed it accordingly.
* I updated invalid section numbers pointing to the section of DAP discussing extensions.
> Fix references

- draft-ietf-ppm-dap-taskprov.md
The extension can also be included in the private extensions; standard DAP semantics will disallow it from being included in both extension mechanisms.
> Allow taskbind extension to be included in public report extensions.
